<target name="javac" depends="javac.helpers">
    <mkdir dir="${AndroidRuntime-classes.dir}" />
    <depend srcdir="src" destdir="${AndroidRuntime-classes.dir}">
      <include name="**/*.java" />
      <exclude name="**/helpers/*.java" />
    </depend>
    <javac target="1.8" source="1.8" destdir="${AndroidRuntime-classes.dir}" srcdir="src" encoding="utf-8"
           includeantruntime="false">
      <classpath>
        <fileset dir="lib/appinventor">
          <include name="*.jar" />
        </fileset>
        <fileset dir="lib/deps">
          <include name="*.jar" />
        </fileset>
      </classpath>
      <include name="**/*.java" />
      <exclude name="**/helpers/*.java" />
    </javac>
  </target>
